import path from "node:path";
import type { MergedConfig } from "../core/merged-config.js";
import type { LoopConfig } from "../core/merged-config.js";
import type { PlannedFile } from "../core/plan.js";
import { OMH_DIR } from "../utils/paths.js";

/**
 * Loop-engine assets.
 *
 * Unlike building blocks — which emit exactly one hook script apiece — the loop
 * engine ships non-hook artifacts: a supervisor runner, and (in later stages)
 * the skill, monitor and ledger templates. They are computed here and written
 * by the same generate/plan pair as everything else, so `omh sync --check`,
 * `omh diff` and `omh doctor` see loop drift too.
 */
export interface LoopAssetOptions {
  projectDir: string;
  config: MergedConfig;
}

function shellSingleQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/**
 * Per-runtime invocation of a single headless, non-resuming turn.
 *
 * The loop deliberately does NOT resume the previous conversation: a fresh
 * session each iteration keeps token use flat, and the ledger plus git log
 * carry the context instead.
 */
function runtimeCommand(loop: LoopConfig): string {
  switch (loop.runtime) {
    case "codex":
      return `codex exec --model ${loop.model} --dangerously-bypass-approvals-and-sandbox "$PROMPT"`;
    case "pi":
      return `pi run --model ${loop.model} --yes "$PROMPT"`;
    case "claude":
    default:
      return `claude --model ${loop.model} --dangerously-skip-permissions -p "$PROMPT"`;
  }
}

function renderRunner(loop: LoopConfig): string {
  const stateDir = `${OMH_DIR}/state`;
  return `#!/usr/bin/env bash
# Generated by oh-my-harness — do not edit. Change harness.yaml and run \`omh sync\`.
#
# Autonomous loop runner. Each iteration is a fresh headless session that reads
# the ledger, executes exactly one work order, verifies it, and commits.
set -uo pipefail

cd "$(dirname "$0")/../.." || exit 1

OMH_LOOP_RUNTIME=${loop.runtime}
OMH_LOOP_MODEL=${shellSingleQuote(loop.model)}
OMH_LOOP_LEDGER=${shellSingleQuote(loop.ledger)}
OMH_LOOP_WORK_ORDERS=${shellSingleQuote(loop.workOrders)}
SENTINEL=${shellSingleQuote(loop.sentinel)}

# Three distinct waits. Conflating them is what burns tokens: a usage limit, a
# crashed turn, and a task waiting on a human are different conditions.
OMH_LOOP_INTERVAL=${loop.interval}          # healthy iteration spacing
OMH_LOOP_LIMIT_BACKOFF=1800                 # provider usage limit reached
OMH_LOOP_EMPTY_BACKOFF=300                  # empty output / crashed turn
OMH_LOOP_BLOCKED_BACKOFF=${loop.blockedBackoff}  # waiting on the architect
OMH_LOOP_BLOCKED_STREAK=3                   # consecutive BLOCKED turns before backing off

STATE_DIR="${stateDir}"
EVENTS="${stateDir}/loop-events.jsonl"
LOG="${stateDir}/loop.log"
STOP_FILE="${stateDir}/loop.stop"
mkdir -p "$STATE_DIR"

emit() {
  # kind, message — appended as JSONL so monitoring never depends on the
  # agent runtime having a notification channel of its own.
  printf '{"ts":"%s","kind":"%s","runtime":"%s","message":%s}\\n' \\
    "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$1" "$OMH_LOOP_RUNTIME" \\
    "$(printf '%s' "$2" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))')" \\
    >> "$EVENTS"
}

PROMPT="Autonomous loop iteration. Read $OMH_LOOP_LEDGER first.
Pick the next unchecked ([ ]) task, read its work order in $OMH_LOOP_WORK_ORDERS/<ID>.md and implement it exactly.
Do not make design decisions of your own. Do not write your own work order: if one is missing, mark the task 'BLOCKED: no work order' and stop.
Run the acceptance commands from the work order before ticking any checkbox.
Update the checkbox and the progress log, then commit.
Print exactly $SENTINEL on the final line ONLY when the whole goal is verified and complete.
Otherwise summarise the remaining tasks in three lines and do not mention that string in any form."

blocked_streak=0
emit start "loop runner started"

while true; do
  if [ -f "$STOP_FILE" ]; then
    emit stop "stop file present"
    break
  fi

  OUT="$(${runtimeCommand(loop)} 2>&1)"
  STATUS=$?
  printf '%s\\n' "$OUT" >> "$LOG"

  # Whole-line match only. \`grep -q\` would fire on a turn that merely mentions
  # the sentinel while explaining it has NOT finished.
  if printf '%s' "$OUT" | tail -n 5 | grep -qx "$SENTINEL"; then
    emit complete "sentinel observed — goal complete"
    break
  fi

  if printf '%s' "$OUT" | grep -qiE "usage limit|limit reached|rate.?limit"; then
    emit limit "usage limit — backing off \${OMH_LOOP_LIMIT_BACKOFF}s"
    sleep "$OMH_LOOP_LIMIT_BACKOFF"
    continue
  fi

  if [ $STATUS -ne 0 ]; then
    if [ -z "$OUT" ]; then
      emit crash "empty output (exit $STATUS) — backing off \${OMH_LOOP_EMPTY_BACKOFF}s"
      sleep "$OMH_LOOP_EMPTY_BACKOFF"
    else
      emit error "turn failed (exit $STATUS)"
      sleep "$OMH_LOOP_INTERVAL"
    fi
    continue
  fi

  if printf '%s' "$OUT" | grep -q "BLOCKED"; then
    blocked_streak=$((blocked_streak + 1))
    emit blocked "BLOCKED turn ($blocked_streak in a row)"
    if [ "$blocked_streak" -ge "$OMH_LOOP_BLOCKED_STREAK" ]; then
      emit waiting "waiting on the architect — backing off \${OMH_LOOP_BLOCKED_BACKOFF}s"
      sleep "$OMH_LOOP_BLOCKED_BACKOFF"
      continue
    fi
  else
    blocked_streak=0
    emit progress "iteration complete"
  fi

  sleep "$OMH_LOOP_INTERVAL"
done
`;
}

export async function computeLoopAssets(options: LoopAssetOptions): Promise<PlannedFile[]> {
  const { projectDir, config } = options;
  if (!config.loop) return [];

  return [
    {
      path: path.join(projectDir, OMH_DIR, "loop", "run.sh"),
      content: renderRunner(config.loop),
      chmod: 0o755,
    },
  ];
}
