import path from "node:path";
import type { MergedConfig } from "../core/merged-config.js";
import type { LoopConfig } from "../core/merged-config.js";
import type { PlannedFile } from "../core/plan.js";
import { OMH_DIR } from "../utils/paths.js";

/**
 * Loop-engine assets.
 *
 * Unlike building blocks — which emit exactly one hook script apiece — the loop
 * engine ships non-hook artifacts: a supervisor runner, and (in later stages)
 * the skill, monitor and ledger templates. They are computed here and written
 * by the same generate/plan pair as everything else, so `omh sync --check`,
 * `omh diff` and `omh doctor` see loop drift too.
 */
export interface LoopAssetOptions {
  projectDir: string;
  config: MergedConfig;
}

function shellSingleQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/**
 * Per-runtime invocation of a single headless, non-resuming turn.
 *
 * The loop deliberately does NOT resume the previous conversation: a fresh
 * session each iteration keeps token use flat, and the ledger plus git log
 * carry the context instead.
 */
function runtimeCommand(loop: LoopConfig): string {
  switch (loop.runtime) {
    case "codex":
      return `codex exec --model "$OMH_LOOP_MODEL" --dangerously-bypass-approvals-and-sandbox "$PROMPT"`;
    case "pi":
      return `pi run --model "$OMH_LOOP_MODEL" --yes "$PROMPT"`;
    case "claude":
    default:
      return `claude --model "$OMH_LOOP_MODEL" --dangerously-skip-permissions -p "$PROMPT"`;
  }
}

function renderRunner(loop: LoopConfig): string {
  const stateDir = `${OMH_DIR}/state`;
  const isolateBlock = loop.isolate
    ? `
# Isolated worktree: the loop commits on its own branch while the architect
# keeps working on theirs. Merge (and re-verify) when the goal completes.
WORKTREE="${OMH_DIR}/loop/worktree"
if [ ! -d "$WORKTREE" ]; then
  git worktree add "$WORKTREE" -b omh-loop >/dev/null 2>&1 \\
    || git worktree add "$WORKTREE" omh-loop >/dev/null 2>&1 \\
    || { echo "omh-loop: git worktree add failed" >&2; exit 1; }
fi
cd "$WORKTREE" || exit 1
`
    : "";
  return `#!/usr/bin/env bash
# Generated by oh-my-harness — do not edit. Change harness.yaml and run \`omh sync\`.
#
# Autonomous loop runner. Each iteration is a fresh headless session that reads
# the ledger, executes exactly one work order, verifies it, and commits.
set -uo pipefail

cd "$(dirname "$0")/../.." || exit 1
PROJECT_ROOT="$(pwd)"

# Inherited by every headless turn and its hooks; loop-guard fires on it.
export OMH_LOOP=1
OMH_LOOP_RUNTIME=${loop.runtime}
OMH_LOOP_MODEL=${shellSingleQuote(loop.model)}
OMH_LOOP_LEDGER=${shellSingleQuote(loop.ledger)}
OMH_LOOP_WORK_ORDERS=${shellSingleQuote(loop.workOrders)}
SENTINEL=${shellSingleQuote(loop.sentinel)}

# Three distinct waits. Conflating them is what burns tokens: a usage limit, a
# crashed turn, and a task waiting on a human are different conditions.
OMH_LOOP_INTERVAL=${loop.interval}          # healthy iteration spacing
OMH_LOOP_LIMIT_BACKOFF=1800                 # provider usage limit reached
OMH_LOOP_EMPTY_BACKOFF=300                  # empty output / crashed turn
OMH_LOOP_BLOCKED_BACKOFF=${loop.blockedBackoff}  # waiting on the architect
OMH_LOOP_BLOCKED_STREAK=3                   # consecutive BLOCKED turns before backing off

${isolateBlock}
# State lives in the main project root either way, so monitoring and the stop
# file work identically with or without the worktree.
STATE_DIR="$PROJECT_ROOT/${stateDir}"
EVENTS="$STATE_DIR/loop-events.jsonl"
LOG="$STATE_DIR/loop.log"
STOP_FILE="$STATE_DIR/loop.stop"
mkdir -p "$STATE_DIR"

# A leftover stop file from the previous run would kill this one instantly.
rm -f "$STOP_FILE"

emit() {
  # kind, message — appended as JSONL so monitoring never depends on the
  # agent runtime having a notification channel of its own.
  printf '{"ts":"%s","kind":"%s","runtime":"%s","message":%s}\\n' \\
    "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$1" "$OMH_LOOP_RUNTIME" \\
    "$(node -p 'JSON.stringify(process.argv[1])' "$2")" \\
    >> "$EVENTS"
}

PROMPT="Autonomous loop iteration. Read $OMH_LOOP_LEDGER first.
Pick the next unchecked ([ ]) task, read its work order in $OMH_LOOP_WORK_ORDERS/<ID>.md and implement it exactly.
Do not make design decisions of your own. Do not write your own work order: if one is missing, mark the task 'BLOCKED: no work order' and stop.
Run the acceptance commands from the work order before ticking any checkbox.
Update the checkbox and the progress log, then commit.
Print exactly $SENTINEL on the final line ONLY when the whole goal is verified and complete.
Otherwise summarise the remaining tasks in three lines and do not mention that string in any form."

blocked_streak=0
emit start "loop runner started"

while true; do
  if [ -f "$STOP_FILE" ]; then
    emit stop "stop file present"
    break
  fi

  OUT="$(${runtimeCommand(loop)} 2>&1)"
  STATUS=$?
  printf '%s\\n' "$OUT" >> "$LOG"

  if printf '%s' "$OUT" | grep -qiE "usage limit|limit reached|rate.?limit"; then
    emit limit "usage limit — backing off \${OMH_LOOP_LIMIT_BACKOFF}s"
    sleep "$OMH_LOOP_LIMIT_BACKOFF"
    continue
  fi

  if [ $STATUS -ne 0 ]; then
    if [ -z "$OUT" ]; then
      emit crash "empty output (exit $STATUS) — backing off \${OMH_LOOP_EMPTY_BACKOFF}s"
      sleep "$OMH_LOOP_EMPTY_BACKOFF"
    else
      emit error "turn failed (exit $STATUS)"
      sleep "$OMH_LOOP_INTERVAL"
    fi
    continue
  fi

  # Whole-line match only, and only on a clean exit: a crashed turn that
  # happened to echo the sentinel must not end the loop as "complete".
  if printf '%s' "$OUT" | tail -n 5 | grep -qx "$SENTINEL"; then
    emit complete "sentinel observed — goal complete"
    break
  fi

  if printf '%s' "$OUT" | grep -q "BLOCKED:"; then
    blocked_streak=$((blocked_streak + 1))
    emit blocked "BLOCKED turn ($blocked_streak in a row)"
    if [ "$blocked_streak" -ge "$OMH_LOOP_BLOCKED_STREAK" ]; then
      emit waiting "waiting on the architect — backing off \${OMH_LOOP_BLOCKED_BACKOFF}s"
      sleep "$OMH_LOOP_BLOCKED_BACKOFF"
      continue
    fi
  else
    blocked_streak=0
    emit progress "iteration complete"
  fi

  sleep "$OMH_LOOP_INTERVAL"
done
`;
}

/**
 * The loop protocol, in one place. It is emitted twice: into CLAUDE.md /
 * AGENTS.md (so every runtime's session carries it) and into the skill. Rules
 * live in the ledger and these managed sections rather than in the runner
 * prompt, because those are what get reloaded on every fresh iteration.
 */
export function renderLoopProtocol(loop: LoopConfig): string {
  const architectOnly =
    loop.architectOnly.length > 0
      ? loop.architectOnly.map((p) => `\`${p}\``).join(", ")
      : "none declared — add paths to `loop.architectOnly` in harness.yaml";
  return `## Autonomous Loop Protocol

The autonomous loop runs one work order per fresh session. \`${loop.ledger}\` is the
single source of truth: goal gates, task checkboxes, decisions and progress log.

- Pick the next unchecked task in \`${loop.ledger}\`; implement it from its work order
  in \`${loop.workOrders}/<ID>.md\`, exactly as written. Make no design decisions.
- No work order, no work. Mark the task \`BLOCKED: no work order\` and stop — never
  write your own work order and then implement it. Self-approval is the failure mode.
- Run the work order's acceptance commands before ticking any checkbox.
- Architect-only, never edited by the loop: ${architectOnly}.
- On a blocker needing a human, or after three failed attempts, mark
  \`BLOCKED: <reason>\` and move on. Never idle waiting for a person.
- One task, one commit. Update the checkbox and the progress log in the same commit.

Start: \`nohup bash .omh/loop/run.sh >/dev/null 2>&1 &\` (stop with \`touch ${OMH_DIR}/state/loop.stop\`).
Watch: \`tail -f ${OMH_DIR}/state/loop-events.jsonl\`.`;
}

function renderSkill(loop: LoopConfig): string {
  return `---
name: omh-loop
description: Set up and start the autonomous loop for a goal. Use when asked to run work as a loop, in a loop, or unattended.
---

# Autonomous loop

You are the architect, not the loop. Set it up, start it, then carry on with
your own work — the loop reports through its event log.

1. Write \`${loop.ledger}\`: the goal as verifiable gates, tasks as checkboxes
   grouped by phase, a decisions log and a progress log. Exclude anything needing
   the user's own action (store submission, console access) from the goal.
2. Write a work order per task in \`${loop.workOrders}/<ID>.md\`: file paths, signatures,
   thresholds, exact copy, forbidden changes, acceptance criteria and the command
   that verifies it. Include work outside the code the task implies — deploy
   scripts, env, migrations, allowlists — the loop will not infer them.
   Queue several ahead: a loop with no work order left spins doing nothing.
3. Name the files only you may touch in \`loop.architectOnly\` (harness.yaml, then
   \`omh sync\`). An abstract "do not improvise" is not obeyed; a named path is.
4. Start it in the background — a foreground start blocks your session for hours:
   \`nohup bash .omh/loop/run.sh >/dev/null 2>&1 &\`${loop.isolate ? " (runs in its own git worktree so you can keep working)" : ""}.
5. Attach monitoring immediately — do not wait to be asked for progress:
   \`tail -f ${OMH_DIR}/state/loop-events.jsonl\` and \`tail -n 0 -F .git/logs/HEAD\`.
   Watch for failure signatures too (\`blocked\`, \`limit\`, \`crash\`), not just success:
   otherwise a dead loop looks exactly like a quiet one.

${renderLoopProtocol(loop)}
`;
}

/** The paths computeLoopAssets can emit — used to clean up when the loop is disabled. */
export function loopAssetPaths(projectDir: string): string[] {
  return [
    path.join(projectDir, OMH_DIR, "loop", "run.sh"),
    path.join(projectDir, ".claude", "skills", "omh-loop", "SKILL.md"),
  ];
}

export async function computeLoopAssets(options: LoopAssetOptions): Promise<PlannedFile[]> {
  const { projectDir, config } = options;
  if (!config.loop) return [];

  return [
    {
      path: path.join(projectDir, OMH_DIR, "loop", "run.sh"),
      content: renderRunner(config.loop),
      chmod: 0o755,
    },
    {
      path: path.join(projectDir, ".claude", "skills", "omh-loop", "SKILL.md"),
      content: renderSkill(config.loop),
    },
  ];
}
