import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { HooksOutput } from "./hooks.js";

/**
 * Pi (pi.dev) emitter.
 *
 * Pi hooks are TypeScript extensions (`pi.on("tool_call", ...)`), not shell
 * scripts. Rather than re-implement every catalog block in TypeScript, the
 * emitter generates a thin *bridge* extension that shells out to the same
 * `.omh/hooks/*.sh` scripts the Claude and Codex emitters use — keeping a
 * single source of truth for block logic.
 *
 * The bridge always sends a Claude-style payload (a `transcript_path` field is
 * present), so the runtime-detecting `_emit_decision` in each script emits
 * `permissionDecision:"ask"` for ask-mode blocks and `decision:"block"` for
 * block-mode blocks. The bridge maps those back onto Pi's native primitives:
 * `ctx.ui.select` for ask, `{ block: true }` for block.
 */

export interface PiBinding {
  /** Pi tool names this binding intercepts (e.g. ["edit", "write"]). */
  tools: string[];
  /**
   * The exact shell command line that runs the generated hook, as emitted into
   * the Claude/Codex settings (e.g. `bash '/abs/.omh/hooks/foo.sh'`). The bridge
   * runs it through a shell so the format stays identical across all emitters.
   */
  command: string;
}

const PI_EXTENSION_DIR = ".pi/extensions";
const PI_EXTENSION_FILE = "omh-harness.ts";

// Claude/catalog matcher tool names -> Pi tool names. Pi exposes lowercase
// built-in tools: bash, read, edit, write, grep, find, ls.
const MATCHER_TO_PI_TOOL: Record<string, string> = {
  bash: "bash",
  edit: "edit",
  write: "write",
  read: "read",
  grep: "grep",
  find: "find",
  ls: "ls",
};

/**
 * Translate a catalog matcher (e.g. "Edit|Write") into the set of Pi tool
 * names the bridge should intercept. Unknown tokens are dropped.
 */
function matcherToPiTools(matcher: string): string[] {
  const tools: string[] = [];
  for (const token of matcher.split("|")) {
    const pi = MATCHER_TO_PI_TOOL[token.trim().toLowerCase()];
    if (pi && !tools.includes(pi)) tools.push(pi);
  }
  return tools;
}

/**
 * Extract the PreToolUse bindings the Pi bridge can express. Pi's `tool_call`
 * event fires before execution and can block, which maps onto PreToolUse.
 * Other events (PostToolUse, SessionStart, ...) have no `tool_call` equivalent
 * and are skipped for now.
 */
export function extractPiBindings(hooksConfig: HooksOutput["hooksConfig"]): PiBinding[] {
  const pre = hooksConfig["PreToolUse"] ?? [];
  const bindings: PiBinding[] = [];
  for (const entry of pre) {
    const tools = matcherToPiTools(entry.matcher);
    if (tools.length === 0) continue;
    for (const hook of entry.hooks) {
      bindings.push({ tools, command: hook.command });
    }
  }
  return bindings;
}

/**
 * Render the bridge extension TypeScript source for the given bindings.
 * Pure (no IO) so it can be unit-tested.
 */
export function buildPiExtension(bindings: PiBinding[]): string {
  const bindingLiterals = bindings
    .map((b) => `  { tools: ${JSON.stringify(b.tools)}, command: ${JSON.stringify(b.command)} },`)
    .join("\n");

  return `// AUTO-GENERATED by oh-my-harness. Do not edit by hand.
//
// Bridges oh-my-harness catalog hooks onto the Pi coding agent. Each binding
// shells out to a generated .omh/hooks/*.sh script (the single source of truth
// shared with the Claude and Codex emitters) and maps its decision onto Pi's
// native tool_call result.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { spawnSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

interface Binding {
  tools: string[];
  command: string;
}

const BINDINGS: Binding[] = [
${bindingLiterals}
];

// .pi/extensions/omh-harness.ts -> project root is three levels up.
const PROJECT_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

// Map a Pi tool_call onto the Claude-style payload the shell hooks expect.
// A transcript_path field marks the payload as Claude-like so ask-mode hooks
// emit permissionDecision:"ask" instead of a hard block.
function buildPayload(toolName: string, input: Record<string, unknown>): unknown {
  const base = { transcript_path: "pi", hook_event_name: "PreToolUse" };
  switch (toolName) {
    case "bash":
      return { ...base, tool_name: "Bash", tool_input: { command: input.command ?? "" } };
    case "edit":
      return { ...base, tool_name: "Edit", tool_input: { file_path: input.path ?? "" } };
    case "write":
      return { ...base, tool_name: "Write", tool_input: { file_path: input.path ?? "", content: input.content ?? "" } };
    case "read":
      return { ...base, tool_name: "Read", tool_input: { file_path: input.path ?? "" } };
    default:
      return { ...base, tool_name: toolName, tool_input: input };
  }
}

export default function (pi: ExtensionAPI) {
  pi.on("tool_call", async (event, ctx) => {
    for (const binding of BINDINGS) {
      if (!binding.tools.includes(event.toolName)) continue;

      const payload = buildPayload(event.toolName, event.input as Record<string, unknown>);
      // binding.command is a full shell command line (e.g. bash '/abs/foo.sh'),
      // identical to what Claude/Codex settings invoke — run it through a shell.
      const proc = spawnSync(binding.command, {
        cwd: PROJECT_ROOT,
        input: JSON.stringify(payload),
        encoding: "utf-8",
        timeout: 10000,
        shell: true,
      });

      const out = (proc.stdout ?? "").trim();
      if (!out) continue;

      let decision: any;
      try {
        decision = JSON.parse(out);
      } catch {
        continue; // non-JSON output is treated as a pass-through
      }

      const isAsk = decision?.hookSpecificOutput?.permissionDecision === "ask";
      const isBlock = decision?.decision === "block" || decision?.hookSpecificOutput?.permissionDecision === "deny";
      const reason: string =
        decision?.hookSpecificOutput?.permissionDecisionReason ??
        decision?.reason ??
        "blocked by oh-my-harness";

      if (isAsk) {
        if (!ctx.hasUI) {
          return { block: true, reason: reason + " (no UI to confirm)" };
        }
        const choice = await ctx.ui.select(\`oh-my-harness — approve this action?\\n\\n  \${reason}\`, ["Yes", "No"]);
        if (choice !== "Yes") {
          return { block: true, reason: "declined by user" };
        }
        continue; // approved — keep checking remaining bindings
      }

      if (isBlock) {
        return { block: true, reason };
      }
    }
    return undefined;
  });
}
`;
}

export interface GeneratePiExtensionOptions {
  projectDir: string;
  hooksOutput: HooksOutput;
}

/**
 * Write the Pi bridge extension to .pi/extensions/omh-harness.ts. Returns the
 * list of generated file paths (empty when there are no PreToolUse bindings,
 * in which case no file is written).
 */
export async function generatePiExtension(options: GeneratePiExtensionOptions): Promise<string[]> {
  const { projectDir, hooksOutput } = options;
  const bindings = extractPiBindings(hooksOutput.hooksConfig);
  if (bindings.length === 0) return [];

  const dir = join(projectDir, PI_EXTENSION_DIR);
  await mkdir(dir, { recursive: true });
  const filePath = join(dir, PI_EXTENSION_FILE);
  await writeFile(filePath, buildPiExtension(bindings), "utf-8");
  return [filePath];
}
