import fs from "node:fs/promises";
import path from "node:path";
import { parse } from "smol-toml";
import { OMH_HOOKS_DIR } from "../../utils/paths.js";
import { computeDrift, HarnessNotFoundError } from "../../core/drift.js";
import { loadProviderConfig } from "../../nl/config-store.js";

export interface DoctorOptions {
  projectDir?: string;
  /** When true, treat drift (out-of-sync generated files) as a health failure. */
  strict?: boolean;
}

export interface DoctorResult {
  healthy: boolean;
  exitCode: number;
  checks: {
    stateFile: boolean;
    claudeMd: boolean;
    agentsMd: boolean;
    settingsJson: boolean;
    codexConfig: boolean;
    piConfig: boolean;
    hooksExecutable: boolean;
  };
  /**
   * Whether generated files are up to date with harness.yaml. undefined when
   * there is no harness.yaml (drift not evaluated). Drift is a non-fatal
   * warning unless `strict` is set.
   */
  inSync?: boolean;
  /**
   * Whether an AI provider is configured for natural-language mode
   * (~/.omh/config.json). Informational only — it never affects health, since
   * the provider is global and optional. Surfaced so users can discover
   * `omh config` to rotate an expired key or switch provider/model.
   */
  providerConfigured: boolean;
  messages: string[];
}

export async function doctorCommand(options: DoctorOptions = {}): Promise<DoctorResult> {
  const projectDir = options.projectDir ?? process.cwd();
  const messages: string[] = [];

  const checks = {
    stateFile: false,
    claudeMd: false,
    agentsMd: false,
    settingsJson: false,
    codexConfig: false,
    piConfig: false,
    hooksExecutable: false,
  };

  // 1. Check .claude/oh-my-harness.json exists
  const stateFile = path.join(projectDir, ".claude", "oh-my-harness.json");
  try {
    await fs.access(stateFile);
    checks.stateFile = true;
  } catch {
    messages.push("FAIL: .claude/oh-my-harness.json not found. Run `oh-my-harness init` first.");
  }

  // 2. Check CLAUDE.md exists and has managed markers
  const claudeMdPath = path.join(projectDir, "CLAUDE.md");
  try {
    const content = await fs.readFile(claudeMdPath, "utf-8");
    if (content.includes("<!-- oh-my-harness:")) {
      checks.claudeMd = true;
    } else {
      messages.push("WARN: CLAUDE.md exists but has no oh-my-harness managed sections.");
      checks.claudeMd = true; // File exists, just no markers — acceptable
    }
  } catch {
    messages.push("FAIL: CLAUDE.md not found.");
  }

  // 3. Check settings.json exists and is valid JSON
  const settingsPath = path.join(projectDir, ".claude", "settings.json");
  try {
    const raw = await fs.readFile(settingsPath, "utf-8");
    JSON.parse(raw);
    checks.settingsJson = true;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") {
      messages.push("FAIL: .claude/settings.json not found.");
    } else {
      messages.push("FAIL: .claude/settings.json is not valid JSON.");
    }
  }

  // 4. AGENTS.md (Codex)
  const agentsMdPath = path.join(projectDir, "AGENTS.md");
  try {
    await fs.access(agentsMdPath);
    checks.agentsMd = true;
  } catch {
    messages.push("FAIL: AGENTS.md not found.");
  }

  // 5. .codex/hooks.json + .codex/config.toml — both must exist AND parse.
  const codexHooksPath = path.join(projectDir, ".codex", "hooks.json");
  const codexTomlPath = path.join(projectDir, ".codex", "config.toml");
  try {
    JSON.parse(await fs.readFile(codexHooksPath, "utf-8"));
    const tomlRaw = await fs.readFile(codexTomlPath, "utf-8");
    const parsed = parse(tomlRaw) as { features?: { hooks?: unknown; codex_hooks?: unknown; goals?: unknown } };
    if (parsed.features?.hooks !== true) {
      messages.push(
        parsed.features?.codex_hooks === true
          ? "FAIL: .codex/config.toml uses deprecated [features] codex_hooks; run `omh sync` to migrate to hooks = true."
          : "FAIL: .codex/config.toml missing [features] hooks = true.",
      );
    } else if (parsed.features?.goals !== true) {
      messages.push("FAIL: .codex/config.toml missing [features] goals = true.");
    } else {
      checks.codexConfig = true;
    }
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") {
      messages.push("FAIL: .codex/hooks.json or .codex/config.toml not found.");
    } else {
      messages.push("FAIL: .codex/hooks.json or .codex/config.toml is invalid or unreadable.");
    }
  }

  // 6. Pi bridge extension (.pi/extensions/omh-harness.ts). Only generated when
  // PreToolUse hooks exist, so absence is acceptable; a present-but-corrupt file
  // (hand-edit / merge conflict) is a failure.
  const piExtPath = path.join(projectDir, ".pi", "extensions", "omh-harness.ts");
  try {
    const raw = await fs.readFile(piExtPath, "utf-8");
    if (raw.includes("AUTO-GENERATED by oh-my-harness") && raw.includes('pi.on("tool_call"')) {
      checks.piConfig = true;
    } else {
      messages.push(
        "FAIL: .pi/extensions/omh-harness.ts exists but is not a valid oh-my-harness bridge; run `omh sync`.",
      );
    }
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") {
      checks.piConfig = true; // no Pi extension — acceptable
    } else {
      messages.push("FAIL: .pi/extensions/omh-harness.ts is unreadable.");
    }
  }

  // 7. Check hook scripts exist and are executable
  const hooksDir = path.join(projectDir, OMH_HOOKS_DIR);
  try {
    const files = await fs.readdir(hooksDir);
    const scripts = files.filter((f) => f.endsWith(".sh"));
    let allExecutable = true;

    for (const script of scripts) {
      const scriptPath = path.join(hooksDir, script);
      try {
        await fs.access(scriptPath, fs.constants.X_OK);
      } catch {
        messages.push(`FAIL: Hook script not executable: ${script}`);
        allExecutable = false;
      }
    }

    checks.hooksExecutable = allExecutable;
  } catch {
    // No hooks dir — acceptable if no hooks defined
    checks.hooksExecutable = true;
  }

  // 8. Drift: are generated files up to date with harness.yaml? Only evaluated
  // when a harness.yaml is present. Non-fatal by default (a warning), fatal
  // under --strict so CI can gate on it.
  let inSync: boolean | undefined;
  try {
    const drift = await computeDrift(projectDir);
    inSync = drift.inSync;
    if (!drift.inSync) {
      messages.push(
        `${options.strict ? "FAIL" : "WARN"}: generated files are out of sync with harness.yaml — run \`omh sync\`.`,
      );
    } else if (drift.versionDrift) {
      messages.push(
        `WARN: harness generated by oh-my-harness ${drift.versionDrift.manifestVersion}, ` +
          `now running ${drift.versionDrift.currentVersion} — run \`omh sync\` to refresh.`,
      );
    }
  } catch (err) {
    if (!(err instanceof HarnessNotFoundError)) {
      messages.push(`WARN: could not evaluate sync status: ${(err as Error).message}`);
    }
    // No harness.yaml → leave inSync undefined (drift not applicable).
  }

  // 9. AI provider config (~/.omh/config.json). Global and optional, so this is
  // purely informational (INFO) and never affects health — it just surfaces
  // `omh config` so users can rotate an expired key or switch provider/model.
  const providerConfigured = await checkProviderConfig(messages);

  const checksHealthy = Object.values(checks).every(Boolean);
  const healthy = checksHealthy && (!options.strict || inSync !== false);
  const exitCode = healthy ? 0 : 1;

  if (healthy) {
    console.log("oh-my-harness: all checks passed");
    for (const msg of messages) {
      console.log(`  ${msg}`);
    }
  } else {
    console.log("oh-my-harness: some checks failed:");
    for (const msg of messages) {
      console.log(`  ${msg}`);
    }
  }

  return { healthy, exitCode, checks, inSync, providerConfigured, messages };
}

/**
 * Inspects the global AI provider config and appends an INFO hint to `messages`.
 * Returns whether a provider is configured. Never reads or echoes the API key.
 */
async function checkProviderConfig(messages: string[]): Promise<boolean> {
  const config = await loadProviderConfig();

  if (!config) {
    messages.push(
      "INFO: No AI provider configured for natural-language mode — run `omh config` to set one up.",
    );
    return false;
  }

  if (config.method === "api") {
    const model = config.model ? `, ${config.model}` : "";
    messages.push(
      `INFO: AI provider: ${config.provider} (api${model}). ` +
        "If your API key expired, run `omh config` to update it or switch provider.",
    );
  } else if (config.method === "oauth") {
    const model = config.model ? `, ${config.model}` : "";
    messages.push(
      `INFO: AI provider: ${config.provider} (oauth${model}). ` +
        "Uses Codex CLI auth; run `codex login` if the session expired.",
    );
  } else {
    messages.push(
      `INFO: AI provider: ${config.provider} (cli). Run \`omh config\` to switch provider or model.`,
    );
  }

  return true;
}
