import fs from "node:fs/promises";
import path from "node:path";
import yaml from "js-yaml";
import chalk from "chalk";
import { HarnessConfigSchema } from "../../core/harness-schema.js";
import { harnessToMergedConfigV2 } from "../../core/harness-converter-v2.js";
import { generate } from "../../core/generator.js";
import { computeDrift, HarnessNotFoundError } from "../../core/drift.js";
import { writeHarnessState } from "./init.js";

export interface SyncOptions {
  projectDir?: string;
  /** When true, report drift without writing and exit non-zero if out of date. */
  check?: boolean;
}

export interface SyncResult {
  exitCode: number;
  inSync?: boolean;
}

export async function syncCommand(options: SyncOptions = {}): Promise<SyncResult> {
  const projectDir = options.projectDir ?? process.cwd();
  const harnessYamlPath = path.join(projectDir, "harness.yaml");

  if (options.check) {
    return runCheck(projectDir);
  }

  let raw: string | undefined;
  try {
    raw = await fs.readFile(harnessYamlPath, "utf-8");
  } catch (err) {
    const error = err as NodeJS.ErrnoException;
    if (error.code === "ENOENT") {
      console.error(chalk.red(`harness.yaml not found at ${harnessYamlPath}`));
      console.error("Run `oh-my-harness init` to create one.");
    } else {
      console.error(chalk.red(`Failed to read harness.yaml: ${error.message}`));
    }
    process.exit(1);
    return { exitCode: 1 };
  }

  let parsed: unknown;
  try {
    parsed = yaml.load(raw);
  } catch (err) {
    const error = err as Error;
    console.error(chalk.red(`Failed to parse harness.yaml: ${error.message}`));
    process.exit(1);
    return { exitCode: 1 };
  }

  const result = HarnessConfigSchema.safeParse(parsed);
  if (!result.success) {
    console.error(chalk.red("harness.yaml validation failed:"));
    for (const issue of result.error.issues) {
      console.error(`  ${issue.path.join(".")}: ${issue.message}`);
    }
    process.exit(1);
    return { exitCode: 1 };
  }

  const harness = result.data;
  const mergedV2 = await harnessToMergedConfigV2(harness, undefined, projectDir);
  if (mergedV2.catalogErrors && mergedV2.catalogErrors.length > 0) {
    for (const err of mergedV2.catalogErrors) {
      console.log(chalk.yellow(`  ⚠ ${err}`));
    }
  }
  const genResult = await generate({ projectDir, config: mergedV2 });
  await writeHarnessState(projectDir, { presets: ["harness"], generatedAt: new Date().toISOString() });

  console.log(chalk.green("oh-my-harness: sync complete"));
  console.log("Generated files:");
  for (const f of genResult.files) {
    console.log(`  ${f}`);
  }
  return { exitCode: 0 };
}

/**
 * `omh sync --check`: report whether generated files are up to date with
 * harness.yaml without writing anything. exitCode 0 = in sync, 1 = drift (or a
 * harness.yaml problem). CI-friendly, like `prettier --check`.
 */
async function runCheck(projectDir: string): Promise<SyncResult> {
  let drift;
  try {
    drift = await computeDrift(projectDir);
  } catch (err) {
    if (err instanceof HarnessNotFoundError) {
      console.error(chalk.red(err.message));
      console.error("Run `oh-my-harness init` to create one.");
    } else {
      console.error(chalk.red(`sync --check failed: ${(err as Error).message}`));
    }
    return { exitCode: 1 };
  }

  if (drift.inSync) {
    console.log(chalk.green("oh-my-harness: up to date"));
    if (drift.versionDrift) {
      console.log(
        chalk.yellow(
          `  ⚠ generated by oh-my-harness ${drift.versionDrift.manifestVersion}, ` +
            `now running ${drift.versionDrift.currentVersion} — re-run \`omh sync\` to refresh.`,
        ),
      );
    }
    return { exitCode: 0, inSync: true };
  }

  console.error(chalk.red("oh-my-harness: out of sync — run `omh sync`"));
  for (const change of drift.changed) {
    const label = change.kind === "create" ? "would create" : "would update";
    console.error(`  ${label}: ${change.path}`);
  }
  for (const stale of drift.wouldDelete) {
    console.error(`  would delete: ${stale}`);
  }
  return { exitCode: 1, inSync: false };
}
